[theme]
primaryColor="#31333F" # Charcoal grey, hsl(231째, 13%, 22%)
backgroundColor="#FEE7E1" # Light peach, hsl(12째, 94%, 94%)
secondaryBackgroundColor="#E4CfCA" # Pale pink, hsl(12째, 33%, 84%)
textColor="#31333F" # Charcoal grey, hsl(231째, 13%, 22%)
font="sans serif"